// Export package generation (ASSIGNMENT §8).
// Produces a ZIP with: map.json, renderer JS+CSS, assets/, index.html,
// embed.html, README.txt.

import { zipSync, strToU8 } from "fflate";
import type { ClickMapDefinition, Asset } from "@svg-mapper/shared";

export interface ExportOptions {
  /** Inline all assets into map.json as data-URIs instead of separate files. */
  inlineAssets: boolean;
  /** Use the minified renderer bundle (clickmap-renderer.min.js). Not yet built — falls back to regular. */
  minifyRenderer: boolean;
}

export interface ExportPackage {
  zip: Uint8Array;
  embedSnippet: string;
  mapJson: string;
}

// Derive a safe filename slug from an asset name.
function assetFilename(asset: Asset): string {
  const ext = asset.type.split("/")[1] ?? "bin";
  const safeName = asset.name.replace(/[^a-zA-Z0-9._-]/g, "-").replace(/-+/g, "-");
  return `assets/${safeName}.${ext}`;
}

function buildEmbedSnippet(basePath = "/maps/my-map"): string {
  return `<div id="clickmap"></div>

<link rel="stylesheet" href="${basePath}/clickmap-renderer.css">
<script src="${basePath}/clickmap-renderer.js"></script>
<script>
  ClickMapRenderer.create({
    container: "#clickmap",
    definitionUrl: "${basePath}/map.json"
  });
</script>`;
}

function buildIndexHtml(
  definition: ClickMapDefinition,
  rendererJs: string,
  rendererCss: string,
  inlineAssets: boolean,
): string {
  const safeJson = JSON.stringify(
    inlineAssets ? definition : definitionWithAssetPaths(definition),
    null,
    2,
  ).replace(/<\/script>/gi, "\\u003c/script>");

  const projectName = definition.project.name;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(projectName)}</title>
  <style>
${rendererCss}
    html, body { margin: 0; padding: 0; height: 100%; }
    body { display: flex; align-items: center; justify-content: center;
           background: #1a1a1a; }
    #clickmap { width: 100%; max-width: 1200px; }
  </style>
</head>
<body>
  <div id="clickmap"></div>
  <script>
${rendererJs}
  </script>
  <script>
    var definition = ${safeJson};
    ClickMapRenderer.create({ container: "#clickmap", definition: definition });
  </script>
</body>
</html>`;
}

function buildEmbedHtml(basePath = "/maps/my-map"): string {
  return `<!-- Embed snippet: paste into your page's <head> and <body> -->

<!-- In <head>: -->
<link rel="stylesheet" href="${basePath}/clickmap-renderer.css">

<!-- In <body> where the map should appear: -->
<div id="clickmap"></div>

<!-- Before </body>: -->
<script src="${basePath}/clickmap-renderer.js"></script>
<script>
  ClickMapRenderer.create({
    container: "#clickmap",
    definitionUrl: "${basePath}/map.json"
  });
</script>`;
}

function buildReadme(projectName: string): string {
  return `${projectName} — Clickable Map Package
${"=".repeat((projectName + " — Clickable Map Package").length)}

CONTENTS
--------
  index.html           Standalone demo — open in a browser or serve statically
  embed.html           Copy-paste snippet for your own pages
  map.json             Map definition (do not rename)
  clickmap-renderer.js Renderer script (do not rename)
  clickmap-renderer.css Renderer styles (do not rename)
  assets/              Image and SVG files referenced by the map

QUICK START
-----------
1. Upload the entire folder to your web server or CDN.
2. Open embed.html and copy the snippet into your page.
3. Update the three paths (/maps/my-map/...) to match your upload location.
4. The <div id="clickmap"> can be placed anywhere in your page body.

OPENING LOCALLY
---------------
Open index.html directly in a browser (file:// works — assets are embedded).

COMMON ISSUES
-------------
CORS on definitionUrl
  If you load the renderer via <script> but host map.json on a different origin,
  the browser will block the fetch. Upload all files to the same origin, or add
  Access-Control-Allow-Origin: * to the server serving map.json.

Missing assets
  All asset files must be uploaded alongside map.json in the assets/ folder.
  Do not rename or move the files.

Container has no height
  Make sure the element with id="clickmap" has an explicit height set in CSS,
  or its parent has a defined height. The renderer fills 100% of the container.

Multiple instances per page
  Call ClickMapRenderer.create() once per container. Each call returns an
  independent instance; they do not share state.

SUPPORTED BROWSERS
------------------
  Chrome 90+, Firefox 90+, Safari 14+, Edge 90+

Generated by svg-mapper editor.
`;
}

// Replace data-URI srcs with relative asset paths (for non-inline export).
function definitionWithAssetPaths(definition: ClickMapDefinition): ClickMapDefinition {
  const assetMap = new Map<string, string>();
  const assets = definition.assets.map((a) => {
    const path = assetFilename(a);
    assetMap.set(a.id, path);
    return { ...a, src: path, inline: false };
  });

  return { ...definition, assets };
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Data-URI → Uint8Array (strips the header).
function dataUriToBytes(src: string): Uint8Array {
  const comma = src.indexOf(",");
  if (comma === -1) return strToU8(src);
  const meta = src.slice(5, comma);
  const payload = src.slice(comma + 1);
  if (meta.includes("base64")) {
    const binary = atob(payload);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
  }
  return strToU8(decodeURIComponent(payload));
}

export function generateExportPackage(
  definition: ClickMapDefinition,
  rendererJs: string,
  rendererCss: string,
  options: ExportOptions,
): ExportPackage {
  const { inlineAssets } = options;

  // For the ZIP's map.json: inline keeps data-URIs; external rewrites to paths.
  const exportedDefinition = inlineAssets
    ? definition
    : definitionWithAssetPaths(definition);

  const mapJson = JSON.stringify(exportedDefinition, null, 2);
  const embedSnippet = buildEmbedSnippet();

  const files: Record<string, Uint8Array> = {};

  files["map.json"] = strToU8(mapJson);
  files["clickmap-renderer.js"] = strToU8(rendererJs);
  files["clickmap-renderer.css"] = strToU8(rendererCss);
  files["embed.html"] = strToU8(buildEmbedHtml());
  files["index.html"] = strToU8(
    buildIndexHtml(definition, rendererJs, rendererCss, inlineAssets),
  );
  files["README.txt"] = strToU8(buildReadme(definition.project.name));

  // Asset files (only when not inlining).
  if (!inlineAssets) {
    for (const asset of definition.assets) {
      if (asset.src.startsWith("data:") || asset.src.startsWith("<svg")) {
        files[assetFilename(asset)] = dataUriToBytes(asset.src);
      }
    }
  }

  const zip = zipSync(files, { level: 6 });
  return { zip, embedSnippet, mapJson };
}
