// Emits dist/clickmap-renderer.d.ts for the release ZIP (#196): the map
// definition types and the public renderer API in one self-contained UMD
// declaration file. It works both as a module (`import type { ClickMapDefinition }
// from "./clickmap-renderer"`) and for the script-tag global `ClickMapRenderer`.
// The result is type-checked against sample consumers before it is written.
import ts from "typescript";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const typesFile = fileURLToPath(new URL("../shared/types.ts", import.meta.url));
const outFile = fileURLToPath(new URL("dist/clickmap-renderer.d.ts", import.meta.url));

function emitDeclarations(file) {
  let text = "";
  const options = { declaration: true, emitDeclarationOnly: true, strict: true, target: ts.ScriptTarget.ES2018, lib: ["lib.es2018.d.ts", "lib.dom.d.ts"] };
  const host = ts.createCompilerHost(options);
  host.writeFile = (name, data) => {
    if (name.endsWith(".d.ts")) text = data;
  };
  const program = ts.createProgram([file], options, host);
  const result = program.emit();
  const diagnostics = [...ts.getPreEmitDiagnostics(program), ...result.diagnostics];
  if (diagnostics.length) fail(diagnostics);
  if (!/^import /m.test(text)) return text;
  throw new Error("shared/types.ts must stay self-contained to ship as one declaration file.");
}

function fail(diagnostics) {
  const format = { getCanonicalFileName: (f) => f, getCurrentDirectory: () => process.cwd(), getNewLine: () => "\n" };
  console.error(ts.formatDiagnostics(diagnostics, format));
  process.exit(1);
}

const { version } = JSON.parse(readFileSync(new URL("package.json", import.meta.url), "utf8"));
const declarations = `// Type declarations for clickmap-renderer.js (svg-mapper renderer ${version}).
// Generated by renderer/build-types.mjs from shared/types.ts; do not edit.
// The map.json contract is also published as clickmap-definition.schema.json.

${emitDeclarations(typesFile).trim()}

/**
 * Mounts a map into \`options.container\`. Exactly one of \`definition\` or
 * \`definitionUrl\` is required. Load failures are reported through the
 * returned instance's "error" event (codes in docs/renderer-api.md).
 */
export declare function create(options: RendererOptions): ClickMapInstance;

/** The script-tag global exposed by clickmap-renderer.js. */
export as namespace ClickMapRenderer;
`;

// Sample consumers: a module importing types, and a plain script using the global.
const consumers = {
  "/virtual/module-consumer.ts": `
import type { ClickMapDefinition, ClickMapInstance } from "./clickmap-renderer";
import { create } from "./clickmap-renderer";
declare const definition: ClickMapDefinition;
const map: ClickMapInstance = create({ container: "#map", definition, deepLink: { enabled: true } });
map.on("area:click", (event) => event.areaId.toUpperCase());
map.on("error", (event) => event.code);
const version: string = definition.schemaVersion;
export { version };
`,
  "/virtual/script-consumer.ts": `
const instance = ClickMapRenderer.create({ container: "#map", definitionUrl: "map.json" });
instance.on("view:change", (event) => event.currentViewId);
`,
  "/virtual/clickmap-renderer.d.ts": declarations,
};
const checkOptions = { strict: true, noEmit: true, target: ts.ScriptTarget.ES2018, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, lib: ["lib.es2018.d.ts", "lib.dom.d.ts"], types: [] };
const checkHost = ts.createCompilerHost(checkOptions);
const readFile = checkHost.readFile.bind(checkHost);
const fileExists = checkHost.fileExists.bind(checkHost);
const getSourceFile = checkHost.getSourceFile.bind(checkHost);
checkHost.readFile = (name) => consumers[name] ?? readFile(name);
checkHost.fileExists = (name) => name in consumers || fileExists(name);
const directoryExists = checkHost.directoryExists?.bind(checkHost);
checkHost.directoryExists = (name) => name === "/virtual" || (directoryExists ? directoryExists(name) : true);
checkHost.getSourceFile = (name, languageVersion, ...rest) =>
  name in consumers ? ts.createSourceFile(name, consumers[name], languageVersion) : getSourceFile(name, languageVersion, ...rest);
const checkProgram = ts.createProgram(Object.keys(consumers), checkOptions, checkHost);
const checkDiagnostics = ts.getPreEmitDiagnostics(checkProgram);
if (checkDiagnostics.length) fail(checkDiagnostics);

mkdirSync(fileURLToPath(new URL("dist", import.meta.url)), { recursive: true });
writeFileSync(outFile, declarations);
console.log(`Wrote ${outFile}`);
